### ISSUE TITLE
Apache configuration file

### ISSUE THREAD

**Issue by pwalter-ebi** [ebiwd/EBI-Corporatesite#1]
Create a file as part of the gulp process, containing something like this for apache configuration - listing all sources pages and their destinations

```
RewriteRule ^/test$ /static/test/index.html [L]
RewriteRule ^/foo/bar$ /static/foo/bar/index.html [L]
```

**Comment by khawkins98** [comment]
Here's what I've got it generating:
```
# a test apache config
RewriteRule ^/index.html$ /static/index.html [L]
RewriteRule ^/sample/training.html$ /static/sample/training.html [L]
```

That useful?

Anything else you need in the file? 

Particular filename? I have `apache_config.txt` at the moment.
