### ISSUE TITLE
Small correction to https://www.ebi.ac.uk/about/our-impact

### ISSUE THREAD

**Issue by pwalter-ebi** [ebiwd/EBI-Corporatesite#19]
From: https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=387947 from Robert Petryszak

there’s a superfluous ’not have’ in 'said they could not have neither have created/collected the last data they used themselves, nor obtained it elsewhere' at the bottom of https://www.ebi.ac.uk/about/our-impact#'

![image](https://user-images.githubusercontent.com/13538087/72343953-0399ed80-36c8-11ea-82bc-01e399fb3993.png)

**Comment by khawkins98** [comment]
+1

Just pushed a fix. https://github.com/ebiwd/EBI-Corporatesite/commit/3488ce0075e008d391fbef8d857ea469653d77c7

**Comment by khawkins98** [comment]
I'll update the ticket once it's on the live site.

- http://wwwdev.ebi.ac.uk/about/our-impact
