### ISSUE TITLE
Linking to off-domain image 

### ISSUE THREAD

**Issue by pwalter-ebi** [ebiwd/EBI-Corporatesite#2]
In the about/contact map there is a link to
http://www.sanger.ac.uk/sites/default/files/styles/1050_wide_/public/wgc_logo_landscapebig6.jpg

We need to remove the protocol so that the page does not give a mixed mode failure, also copy the image to our own infrastructure.

**Comment by khawkins98** [comment]
Finally swapped to use protocol relative. Also agree on getting those images hosted on our server -- do we have a best practice for this?

I wonder if it's worth creating an "EBI-Assets" git repo that could be a way to collaboratively manage/version some reusable things... logos, PPT/DOC templates.

**Comment by khawkins98** [comment]
Closing this. We now have embl.org/files and emblstatic.net
