### ISSUE TITLE
Getting rid of heavy assets from repo and move in Drupal site filesystem

### ISSUE THREAD

**Issue by sandykadam** [ebiwd/EBI-Corporatesite#22]
There are some heavy assets in this repo which makes process slow while pushing/cloning repo and it will be more slow when tags will grow.

This is 11MB file, we should get rid of - `https://github.com/ebiwd/EBI-Corporatesite/blob/master/src/about/our-impact/video-teaser.psd`

Below are some heavy assets like PDF,jpg files, which I can think can upload in Drupal site of ebi.ac.uk - 
`https://github.com/ebiwd/EBI-Corporatesite/tree/master/src/about/digital-bookshelf/publications`

And we can link html to respective asset path from Drupal e.g `https://www.ebi.ac.uk/sites/ebi.ac.uk/files/digital-bookshelf/publications/EMBL-EBI_Impact_report-2016-summary.pdf`

@khawkins98 what do you think?

**Comment by khawkins98** [comment]
I think this has been done. Closing.
